### ISSUE TITLE
lgtv scan not working

### ISSUE THREAD

**Issue by Person2099** [klattimer/LGWebOSRemote#92]
Upon running the `lgtv scan` command I receive an unrecognisable output: (personal details are #'ed)

> Unknown device
b'HTTP/1.1 200 OK\r\nHOST: ###.###.###.###:1900\r\nEXT:\r\nCACHE-CONTROL: max-age=100\r\nLOCATION: http://###.###.###.###:80/description.xml\r\nSERVER: Hue/1.0 UPnP/1.0 IpBridge/1.45.0\r\nhue-bridgeid: 001788FFFEAF4BEA\r\nST: upnp:rootdevice\r\nUSN: uuid:########-####-####-####-############::upnp:rootdevice\r\n\r\n' ('###.###.###.###', 1900)
Traceback (most recent call last):
  File "/Users/keets/.local/bin/lgtv", line 8, in <module>
    sys.exit(main())
  File "/Users/keets/.local/pipx/venvs/lgtv/lib/python3.9/site-packages/LGTV/__init__.py", line 111, in main
    results = LGTVScan()
  File "/Users/keets/.local/pipx/venvs/lgtv/lib/python3.9/site-packages/LGTV/scan.py", line 28, in LGTVScan
    uuid = re.findall(r'uuid:(.*?):', line.decode('utf-8'))[0]
IndexError: list index out of range

**Comment by klattimer** [comment]
Commit 126d1cfaa7c5f12c437e089648ca1c259eb6bc02 should fix it. 

Please report back here with the value for USN as reported by the updated scanning tool.

**Comment by Person2099** [comment]
I have ensured the most recent commit is installed however the error still persists. The current error is below:
<img width="1440" alt="Screen Shot 2021-09-01 at 5 24 05 pm" src="https://user-images.githubusercontent.com/51016337/131630428-b150007b-614a-48e9-afee-630d2fca916e.png">

**Comment by klattimer** [comment]
That's great, I just pushed a small change should get you past that, you're right it's your hue bulb and it appears the /r/n's are confusing the regex. Please check and close issue when done.

**Comment by Person2099** [comment]
Unfortunately that doesn't seem to be the only issue I'm running into.
I have attached the response I get now:
<img width="565" alt="Screen Shot 2021-09-02 at 8 04 58 pm" src="https://user-images.githubusercontent.com/51016337/131825222-5bf8aea5-5800-49cb-8cdf-fc47a8ffd3cf.png">

**Comment by Person2099** [comment]
I completely uninstalled and reinstalled the latest commit and that seems to have fixed the issue. Thank You!

**Comment by cdam06** [comment]
> I completely uninstalled and reinstalled the latest commit and that seems to have fixed the issue. Thank You!

This may be a dumb question, but how do I go about uninstalling and doing a fresh install again?
